
[features]
CodeSpaces = false
Clipboard  = true
Logging    = false
Timeout    = 0.1
Savebrace  = true

[style]
Margin          = 0
ListIndent      = 2
PrettyPad       = false
PrettyBroken    = false
Width           = 0
HSV     = [0.2, 0.1, 0.6]
Dark    = { H = 1.00, S = 1.50, V = 0.25 }
Mid     = { H = 1.00, S = 1.00, V = 0.50 }
Symbol  = { H = 1.00, S = 1.00, V = 1.50 }
Head    = { H = 1.00, S = 1.00, V = 1.75 }
Grey    = { H = 1.00, S = 0.25, V = 1.37 }
Bright  = { H = 1.00, S = 0.70, V = 2.00 }
Syntax  = "gruvbox-dark"
